/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package edu.snu.bike.perank.struts.action;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import edu.snu.bike.perank.struts.form.TestForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-04-2012
 * 
 * XDoclet definition:
 * @struts.action path="/test" name="testForm" input="/test.jsp" scope="request" validate="true"
 */
public class TestAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TestForm testForm = (TestForm) form;// TODO Auto-generated method stub
		return null;
	}
}