package edu.snu.bike.perank.hibernate;

/**
 * Preferencelinkmapping generated by MyEclipse Persistence Tools
 */

public class Preferencelinkmapping implements java.io.Serializable {

	// Fields

	private PreferencelinkmappingId id;

	// Constructors

	/** default constructor */
	public Preferencelinkmapping() {
	}

	/** full constructor */
	public Preferencelinkmapping(PreferencelinkmappingId id) {
		this.id = id;
	}

	// Property accessors

	public PreferencelinkmappingId getId() {
		return this.id;
	}

	public void setId(PreferencelinkmappingId id) {
		this.id = id;
	}

}