package edu.snu.bike.perank.hibernate;

import java.util.HashSet;
import java.util.Set;

/**
 * Preferencetable generated by MyEclipse Persistence Tools
 */

public class PreferenceTable implements java.io.Serializable {

	// Fields

	private Integer id;

	private UserTable usertable;

	private String iswork;

	private Integer month;

	private Integer year;

	private Set preferencetopicmappings = new HashSet(0);

	private Set preferencelinkmappings = new HashSet(0);

	// Constructors

	/** default constructor */
	public PreferenceTable() {
	}

	/** minimal constructor */
	public PreferenceTable(UserTable usertable) {
		this.usertable = usertable;
	}

	/** full constructor */
	public PreferenceTable(UserTable usertable, String iswork, Integer month,
			Integer year, Set preferencetopicmappings,
			Set preferencelinkmappings) {
		this.usertable = usertable;
		this.iswork = iswork;
		this.month = month;
		this.year = year;
		this.preferencetopicmappings = preferencetopicmappings;
		this.preferencelinkmappings = preferencelinkmappings;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public UserTable getUsertable() {
		return this.usertable;
	}

	public void setUsertable(UserTable usertable) {
		this.usertable = usertable;
	}

	public String getIswork() {
		return this.iswork;
	}

	public void setIswork(String iswork) {
		this.iswork = iswork;
	}

	public Integer getMonth() {
		return this.month;
	}

	public void setMonth(Integer month) {
		this.month = month;
	}

	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public Set getPreferencetopicmappings() {
		return this.preferencetopicmappings;
	}

	public void setPreferencetopicmappings(Set preferencetopicmappings) {
		this.preferencetopicmappings = preferencetopicmappings;
	}

	public Set getPreferencelinkmappings() {
		return this.preferencelinkmappings;
	}

	public void setPreferencelinkmappings(Set preferencelinkmappings) {
		this.preferencelinkmappings = preferencelinkmappings;
	}

}