package edu.snu.bike.perank.hibernate;

/**
 * PreferencetopicmappingId generated by MyEclipse Persistence Tools
 */

public class PreferenceTopicMappingId implements java.io.Serializable {

	// Fields

	private PreferenceTable preferencetable;

	private TopicInterestTable topicintresttable;

	// Constructors

	/** default constructor */
	public PreferenceTopicMappingId() {
	}

	/** full constructor */
	public PreferenceTopicMappingId(PreferenceTable preferencetable,
			TopicInterestTable topicintresttable) {
		this.preferencetable = preferencetable;
		this.topicintresttable = topicintresttable;
	}

	// Property accessors

	public PreferenceTable getPreferencetable() {
		return this.preferencetable;
	}

	public void setPreferencetable(PreferenceTable preferencetable) {
		this.preferencetable = preferencetable;
	}

	public TopicInterestTable getTopicintresttable() {
		return this.topicintresttable;
	}

	public void setTopicintresttable(TopicInterestTable topicintresttable) {
		this.topicintresttable = topicintresttable;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PreferenceTopicMappingId))
			return false;
		PreferenceTopicMappingId castOther = (PreferenceTopicMappingId) other;

		return ((this.getPreferencetable() == castOther.getPreferencetable()) || (this
				.getPreferencetable() != null
				&& castOther.getPreferencetable() != null && this
				.getPreferencetable().equals(castOther.getPreferencetable())))
				&& ((this.getTopicintresttable() == castOther
						.getTopicintresttable()) || (this
						.getTopicintresttable() != null
						&& castOther.getTopicintresttable() != null && this
						.getTopicintresttable().equals(
								castOther.getTopicintresttable())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPreferencetable() == null ? 0 : this.getPreferencetable()
						.hashCode());
		result = 37
				* result
				+ (getTopicintresttable() == null ? 0 : this
						.getTopicintresttable().hashCode());
		return result;
	}

}