package edu.snu.bike.perank.hibernate;

/**
 * Preferencelinkmapping generated by MyEclipse Persistence Tools
 */

public class PreferenceLinkMapping implements java.io.Serializable {

	// Fields

	private PreferenceLinkMappingId id;

	// Constructors

	/** default constructor */
	public PreferenceLinkMapping() {
	}

	/** full constructor */
	public PreferenceLinkMapping(PreferenceLinkMappingId id) {
		this.id = id;
	}

	// Property accessors

	public PreferenceLinkMappingId getId() {
		return this.id;
	}

	public void setId(PreferenceLinkMappingId id) {
		this.id = id;
	}

}