package edu.snu.bike.perank.hibernate;

/**
 * Preferencetopicmapping generated by MyEclipse Persistence Tools
 */

public class Preferencetopicmapping implements java.io.Serializable {

	// Fields

	private PreferencetopicmappingId id;

	// Constructors

	/** default constructor */
	public Preferencetopicmapping() {
	}

	/** full constructor */
	public Preferencetopicmapping(PreferencetopicmappingId id) {
		this.id = id;
	}

	// Property accessors

	public PreferencetopicmappingId getId() {
		return this.id;
	}

	public void setId(PreferencetopicmappingId id) {
		this.id = id;
	}

}