package edu.snu.bike.perank.hibernate;

/**
 * PreferencetopicmappingId generated by MyEclipse Persistence Tools
 */

public class PreferencetopicmappingId implements java.io.Serializable {

	// Fields

	private Preferencetable preferencetable;

	private Topicintresttable topicintresttable;

	// Constructors

	/** default constructor */
	public PreferencetopicmappingId() {
	}

	/** full constructor */
	public PreferencetopicmappingId(Preferencetable preferencetable,
			Topicintresttable topicintresttable) {
		this.preferencetable = preferencetable;
		this.topicintresttable = topicintresttable;
	}

	// Property accessors

	public Preferencetable getPreferencetable() {
		return this.preferencetable;
	}

	public void setPreferencetable(Preferencetable preferencetable) {
		this.preferencetable = preferencetable;
	}

	public Topicintresttable getTopicintresttable() {
		return this.topicintresttable;
	}

	public void setTopicintresttable(Topicintresttable topicintresttable) {
		this.topicintresttable = topicintresttable;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PreferencetopicmappingId))
			return false;
		PreferencetopicmappingId castOther = (PreferencetopicmappingId) other;

		return ((this.getPreferencetable() == castOther.getPreferencetable()) || (this
				.getPreferencetable() != null
				&& castOther.getPreferencetable() != null && this
				.getPreferencetable().equals(castOther.getPreferencetable())))
				&& ((this.getTopicintresttable() == castOther
						.getTopicintresttable()) || (this
						.getTopicintresttable() != null
						&& castOther.getTopicintresttable() != null && this
						.getTopicintresttable().equals(
								castOther.getTopicintresttable())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPreferencetable() == null ? 0 : this.getPreferencetable()
						.hashCode());
		result = 37
				* result
				+ (getTopicintresttable() == null ? 0 : this
						.getTopicintresttable().hashCode());
		return result;
	}

}