package edu.snu.bike.perank.hibernate;

import java.util.HashSet;
import java.util.Set;

/**
 * Usertable generated by MyEclipse Persistence Tools
 */

public class Usertable implements java.io.Serializable {

	// Fields

	private Integer id;

	private String name;

	private String ip;

	private Set preferencetables = new HashSet(0);

	// Constructors

	/** default constructor */
	public Usertable() {
	}

	/** full constructor */
	public Usertable(String name, String ip, Set preferencetables) {
		this.name = name;
		this.ip = ip;
		this.preferencetables = preferencetables;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Set getPreferencetables() {
		return this.preferencetables;
	}

	public void setPreferencetables(Set preferencetables) {
		this.preferencetables = preferencetables;
	}

}