/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package edu.snu.bike.perank.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 07-04-2012
 * 
 * XDoclet definition:
 * @struts.form name="anonymousSearchForm"
 */
public class AnonymousSearchForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** topic property */
	private String topic;

	/** link property */
	private String link;

	/*
	 * Generated Methods
	 */
	private String query;

	private int pageNum;
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the topic.
	 * @return String
	 */
	public String getTopic() {
		return topic;
	}

	/** 
	 * Set the topic.
	 * @param topic The topic to set
	 */
	public void setTopic(String topic) {
		this.topic = topic;
	}

	/** 
	 * Returns the link.
	 * @return String
	 */
	public String getLink() {
		return link;
	}

	/** 
	 * Set the link.
	 * @param link The link to set
	 */
	public void setLink(String link) {
		this.link = link;
	}

	public String getQuery() {
		return query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

	public int getPageNum() {
		return pageNum;
	}

	public void setPageNum(int pageNum) {
		this.pageNum = pageNum;
	}
}